version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./frontend:/app/static  # mount frontend files into backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
