version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"   # map EC2 port 5000 to container
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"       # serve frontend on port 80 (HTTP)
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
